# Generated by Django 3.1 on 2020-08-28 08:19

from django.db import migrations, models
import django.db.models.deletion
import django_hint.typehint


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=100)),
            ],
            bases=(models.Model, django_hint.typehint.StandardModelType),
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=(models.Model, django_hint.typehint.StandardModelType),
        ),
        migrations.CreateModel(
            name='LaunchPad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rocket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('core', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rocket', to='launches.core')),
            ],
            bases=(models.Model, django_hint.typehint.StandardModelType),
        ),
        migrations.CreateModel(
            name='Launch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('crew', models.ManyToManyField(blank=True, related_name='launches', to='launches.Crew')),
                ('launch_pad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='launches', to='launches.launchpad')),
                ('rocket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='launches', to='launches.rocket')),
            ],
            bases=(models.Model, django_hint.typehint.StandardModelType),
        ),
    ]
